files/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('',index,name="index"),
    path('logout/',logout_page,name="logout"),
    path('login/',login_page,name="login"),
    path('register/',register,name="register"),
    path('search/', search, name='search'),
    path('share_file/<int:file_id>/', share_file, name='share_file'),
   
    path('download/<int:file_id>/', download_file, name='download_file'),

]

filesharing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('files.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





files/models.py
from django.db import models
from django.contrib.auth.models import User

class UploadedFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    shared_with = models.ManyToManyField(User, related_name='shared_files', blank=True)
    def __str__(self) -> str:
        return str(self.user)

files/forms.py
from django import forms
from .models import UploadedFile

class FileUploadForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['title', 'file']

files/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render, redirect,get_object_or_404
from .forms import FileUploadForm
from .models import UploadedFile
from django.http import HttpResponse
from django.conf import settings
import os


# Create your views here.
def index(request):
    if request.method == 'POST':
        print("call")
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            print("enter")
            new_file = form.save(commit=False)
            new_file.user = request.user
            new_file.save()
            print("save")
            return redirect('index') 
    else:
        print("else")
        form = FileUploadForm()
    user_files = UploadedFile.objects.filter(user=request.user.id)
    all_users = User.objects.exclude(id=request.user.id)
    recieved_files = UploadedFile.objects.filter(shared_with=request.user.id)
    shared_by_me = UploadedFile.objects.filter(user=request.user.id, shared_with__isnull=False).exclude(shared_with=request.user.id).distinct()
    return render(request, 'index.html', {'form': form,'user_files': user_files,'all_users':all_users,'recieved_files': recieved_files,'shared_by_me':shared_by_me})
    
def search(request):
    
    query = request.GET.get('query')
    users = User.objects.filter(username__icontains=query)
    user_files = UploadedFile.objects.filter(user__username__icontains=query)
    return render(request, 'search.html', {'users': users, 'user_files': user_files, 'query': query})


def share_file(request, file_id):
    print("call;;;;")
    uploaded_file = get_object_or_404(UploadedFile, id=file_id)
    if request.method == 'POST':
        print("caldedecevevvrtv")
        user_to_share_id = request.POST.get('user_to_share')
        user = User.objects.get(id=user_to_share_id)
        uploaded_file.shared_with.add(user)
        uploaded_file.save()
        messages.success(request, 'File Successfully Shared!!')
        
    else:
         messages.error(request, 'Error In Sharing File!!') 
         
    return redirect('/')
    




def download_file(request, file_id):
    uploaded_file = get_object_or_404(UploadedFile, id=file_id)
    file_path = os.path.join(settings.MEDIA_ROOT, str(uploaded_file.file))
    with open(file_path, 'rb') as file:
        response = HttpResponse(file.read(), content_type='application/force-download')
        response['Content-Disposition'] = f'attachment; filename="{uploaded_file.file.name}"'
        return response











def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
       
        password = request.POST.get('password')
        
        if not User.objects.filter(username=username).exists():
            
            messages.error(request, 'Username does not exists!!!')
            return redirect('/login/')
        
        user=authenticate(username=username,password=password)
        
        if user is None:
            messages.error(request, 'Invalid Password!!!')
            return redirect('/login/')
        else:
            login(request,user)
            return redirect('/')
            
    return render(request,'login.html')

def logout_page(request):
    logout(request)
    return redirect('/')


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        if User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists():
            
            messages.error(request, 'Username or email already exists!!!')
            return redirect('/register/')
        
        user=User.objects.create(username=username,email=email)
        user.set_password(password)
        user.save()
        messages.success(request, 'Registration successful. You can now log in.')
        return redirect('/register/')
    return render(request, 'register.html')




templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Files</title>
    {% comment %} bootstrap {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
 

    {% comment %} BOXICONS {% endcomment %}
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Latest version of jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    <scrip src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
    
</head>
<body>
  
        {% block content %}
        
        {% endblock content %}


</body>

{% block scripts %}{% endblock scripts %}
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<style>
  .custom-form {
    max-width: 400px;
    margin: auto;
  }
  .custom-form label {
    display: block;
    margin-bottom: 5px;
  }
  .custom-form input[type="text"],
  .custom-form input[type="file"],
  .custom-form button {
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    border-radius: 4px;
    border: 1px solid #ccc;
    box-sizing: border-box;
  }
  .custom-form button {
    background-color: #007bff;
    color: white;
    cursor: pointer;
  }
  .file-list {
    max-width: 600px;
    margin: 0 auto;
    background-color: #fff;
    padding: 30px 40px 10px 10px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgb(0 86 255);
    color: black;
  }
  .file-list h1 {
    font-size: 24px;
    margin-bottom: 20px;
  }
 
  .file-item1 {
    list-style: none;
    margin-bottom: 10px;
    padding: 10px;
    border: 1px solid #4835d4;
    box-shadow: 0 0 10px #86b7fe;
    border-radius: 4px;
    background-color: #86b7fe;
    color: #4835d4;
  }
  .file-item1 a {
    color: #f8f9fa;
    text-decoration: none;
  }
  .file-item1 a:hover {
    text-decoration: underline;
  }

  .file-item2 {
    list-style: none;
    margin-bottom: 10px;
    padding: 10px;
    border: 1px solid #ffffff;
    box-shadow: 0 0 10px 0px #4835d4;
    border-radius: 4px;
    background-color: #86b7fe;
    color: #f8f9fa;
  }
  .file-item2 a {
    color: #4835d4;
    text-decoration: none;
  }
  .file-item2 a:hover {
    text-decoration: underline;
  }

  {% comment %} tutu {% endcomment %}
  .bg-indigo{
    background-color:#4835d4;
    border-radius: 0px 10px 10px 0px;
  }
  .bg-white{
    background-color:white;
    border-radius: 10px 0px 0px 10px;
    
  }

  {% comment %} dd {% endcomment %}
  .custom-form-container {
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
}
.custom-form {
    width: 500px; 
}
  
</style>
<div class="px-3 py-2 border-bottom mb-3">
    <div class="container d-flex flex-wrap justify-content-center">
        {% if user.is_authenticated %}
          <form method="get"  action="{% url 'search' %}"class="d-flex col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search">
            <input type="search" name="query" class="form-control" placeholder="Search..." aria-label="Search">
            <button type="submit">Search</button>
          </form>
        {% endif %}
          <div class="text-end">
              {% if user.is_authenticated %}
                  
                  <button type="button" class="btn btn-light text-dark me-2">Welcome,{{user.username}}</button>
                  <a  class="btn btn-primary" href="#Dashboard">Dashboard</a>
                  <button type="submit" class="btn btn-primary" onclick="window.location.href='{% url 'logout' %}'">Logout</button>
                  
                  
              {% else %}
                  <button type="button" class="btn btn-light text-dark me-2" onclick="window.location.href='{% url 'login' %}'">Login</button>
                  <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'register' %}'">Sign-up</button>
              {% endif %}

          </div>
     </div>
</div>

<div>
  {% if user.is_authenticated%}
  
      <div class="mb-3">
        {% for message in messages %}
        
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-{{message.tags}}" role="alert">
                  {{ message }}
                </div>
            {% endif %}
        {% endfor %}
      </div>
      <div class="container custom-form-container">
        <div>
            <h1 class="text-center mt-4 mb-3">Upload File</h1>
            <form method="post" enctype="multipart/form-data" class="custom-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    <input type="text" name="title" id="id_title" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_file">Select File:</label>
                    <input type="file" name="file" id="id_file" class="form-control-file">
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
        </div>
      </div>
    
      <section id="Dashboard"class="h-100 h-custom gradient-custom-2">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12">
              <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                <div class="card-body p-0">
                  <div class="row g-0">
                    <div class="col-lg-6 bg-white">
                      <div class="p-5">
                        <h3 class="fw-normal mb-5" style="color:#4835d4;">Uploaded Files</h3>

                          <ul>
                            {% for file in user_files %}
                              <li class="file-item1 "> 
                                <h3>{{ file.title }}</h3>  
                                
                                <h6>Uploaded at: {{ file.uploaded_at }}</h6>
                              
                                <form class="d-flex" action="{% url 'share_file' file.id %}" method="post">
                                  {% csrf_token %}
                                  <h6 for="user_to_share">Share with:</h6>
                                  <select class="ms-1" id="user_to_share" name="user_to_share">
                                      <option value="">.</option>
                                      {% for user in all_users %}
                                          <option value="{{ user.id }}">{{ user.username }}</option>
                                      {% endfor %}
                                  </select>
                                  <button class="ms-1"type="submit">Share</button>

                                  <h5 class="ms-auto mb-0"><a  href="{{ file.file.url }}">View</a></h5>
                                  
                              </form>
                              
                              </li>
                            {% empty %}
                              <li class="file-item1">No files uploaded yet.</li>
                            {% endfor %}
                          </ul>
                      </div>
                    </div>


                    <div class="col-lg-6 bg-indigo text-white">
                      <div class="p-5">
                        <h3 class="fw-normal mb-5">Recieved Files</h3>  
                        <ul>
                              {% for file in recieved_files %}
                                  <li class="file-item2">
                                    <h3>{{ file.title }}</h3>
                                    <h6>Uploaded at: {{ file.uploaded_at }} </h6>
                                    
                                    
                                    <div class="d-flex">
                                      <h6>Shared by:</h6>
                                      <select style="appearance: none;padding: 0px 5px;"class="ms-1" name="" id="">
                                        <option value="">{{ file.user.username }}</option>
                                      </select>
                                      <h5 class="ms-auto mb-0"><a  href="{{ file.file.url }}">View</a></h5>
                                      <h5 class="ms-2 mb-0"><a href="{% url 'download_file' file.id %}">Download</a></h5>
                                    </div>
                                    
                                  </li>
                          
                              {% empty %}
                                  <li class="file-item2">No  files  Recieved.</li>
                              {% endfor %}
                        </ul>
                        
                        <h3 class="fw-normal mt-2 mb-3">Files Shared</h3>
                        <ul>
                              {% for file in shared_by_me %}
                                  <li class="file-item2">
                                      <h3>{{ file.title }}</h3>
                                      <h6>Uploaded at: {{ file.uploaded_at }} </h6>
                                      <strong>Shared with:</strong>
                                      <ul>
                                          {% for user in file.shared_with.all %}
                                              <li>{{ user.username }}</li>
                                          {% endfor %}
                                      </ul>
                               
                                  </li>
                              {% empty %}
                                  <li class="file-item2">No files shared by you with other users.</li>
                              {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

  {% endif %}
</div>





{% endblock content %}


templates/login.html
{% extends "base.html" %}

{% block content %}


<div class="container mt-5">

  <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>Login</h2>

      <div class="mb-3">
        {% for message in messages %}
        
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-{{message.tags}}" role="alert">
                  {{ message }}
                </div>
            {% endif %}
        {% endfor %}
      </div>

      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input type="text" class="form-control" autocomplete="off" name="username">
   
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" autocomplete="off" name="password">
      </div>

      <p>Don't have an account <a href="/register/">REGISTER</a></p>
     
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  

</div>
{% endblock content %}


templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">

  <form class="col-6 mx-auto card p-3 shadow-lg" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>Register</h2>

      <div class="mb-3">
        {% for message in messages %}
        
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-{{message.tags}}" role="alert">
                  {{ message }}
                </div>
            {% endif %}
        {% endfor %}
      </div>
        
      

      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input type="text" class="form-control" name="username">
   
      </div>

      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email address</label>
        <input type="email" class="form-control" name="email" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
      </div>

      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" name="password">
      </div>
     
      <p>Already have an account <a href="/login/">Login</a></p>
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>


</div>
{% endblock content %}

templates/search.html
{% extends "base.html" %}


{% block content %}
    <style>
        .user-box {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 20px;
        }
        .file-box {
            border: 1px solid #eee;
            padding: 5px;
            margin-left: 20px;
        }
    </style>

    <div class="container">
        <h1>Search Results for "{{ query }}"</h1>

        {% for user in users %}
            <div class="user-box">
                <h2>{{ user.username }}</h2>
                <div class="row">
                    {% for file in user_files %}
                        {% if file.user == user %}
                            <div class="col-lg-4 mb-3">
                                <div class="d-flex file-box">
                                    <p class="mr-3 mb-0">File Title: {{ file.title }}</p> 
                                    <a class="ms-auto mb-0" href="{{ file.file.url }}">View</a>
                           
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% empty %}
            <p>No users found.</p>
        {% endfor %}
    </div>
{% endblock content %}